name: Terraform Destroy Resources

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Update system and install dependencies
      - name: Update system and install latest dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3-pip
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          sudo rm -rf awscliv2.zip aws

      # Step 3: Set up AWS credentials using GitHub Secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1 # Adjust to your desired AWS region (Singapore)

      # Step 4: Set up the latest Terraform CLI
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      # Step 5: Initialize Terraform
      - name: Terraform Init
        working-directory: Lab1-Terraform
        run: terraform init

      # Step 6: Destroy Terraform resources
      - name: Terraform Destroy
        working-directory: Lab1-Terraform
        run: terraform destroy -auto-approve -var-file="terraform.tfvars"
