jobs:
  destroy:
    runs-on: ubuntu-latest
    if: github.event.inputs.destroy == 'true' # Có thể dùng điều kiện nếu cần
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3-pip
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          sudo rm -rf awscliv2.zip aws

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1 # Điều chỉnh vùng theo nhu cầu

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Terraform Destroy
        working-directory: Lab1-Terraform
        run: terraform destroy -var-file="terraform.tfvars" -auto-approve
