name: Terraform Deployment with Checkov

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Update and Install Dependencies
      - name: Update system and install latest dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3-pip
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          sudo rm -rf awscliv2.zip aws

      # Step 3: Set up AWS credentials using GitHub Secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southest-1 # Adjust to your desired AWS region(sing)

      # Step 4: Set up the latest Terraform CLI
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest # This will use the latest available Terraform version

      # Step 5: Install the latest version of Checkov
      - name: Install Checkov
        run: |
          python3 -m pip install --upgrade pip
          pip install --upgrade checkov

      # Step 6: Run Checkov to scan Terraform code for security issues
      - name: Run Checkov scan
        run: checkov -d .
        continue-on-error: true

      # Step 7: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 8: Validate Terraform files
      - name: Terraform Validate
        run: terraform validate

      # Step 9: Plan Terraform deployment with tfvars file
      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars" -out=tfplan

      # Step 10: Apply Terraform deployment with tfvars file
      - name: Terraform Apply
        if: ${{ github.ref == 'refs/heads/main' }}
        run: terraform apply -var-file="terraform.tfvars" -auto-approve tfplan
